### PR TITLE
Just integrate the templates found into our project and fix the issue…

### PR DESCRIPTION
**Pull request by warrenkwchan**
…s. Also, added @material-ui/icons and bootstrap support. You can look at the form by this type the link:http://localhost:3000/Forms. 

Next I will be investigating some Book and Recommendation Api

### CODE REVIEW

**Review by davidzc01 — APPROVED** [review]

**Review by mxg895 — CHANGES_REQUESTED** [review]
Looks like @material-ui/icons and bootstrap are not added to `yarn.lock`. If yarn.lock doesn't update automatically after you call `yarn add <packages>`, make sure you run `yarn` again to ensure `yarn.lock` gets updated. Everything else looks good and ready to be merged.

**Comment by mxg895** [comment]
It looks like all the integrity sha got removed after adding bootstrap and material-ui/icons. I'm not sure why this happened, but I've deleted the old `yarn.lock` file and regenerated one with `yarn install`. I don't know that's the complication with this. I'm not certain of the complication with the possible cause(s) of this deletion or any complication with forcing to add the integrity back by creating a new `yarn.lock` file. @warrenkwchan @zeyuchen97 @MayKikuchi  any thought on this? Does it look like a safe thing to do? Otherwise, this branch should be ready for merge.

**Comment by warrenkwchan** [comment]
> Looks like @material-ui/icons and bootstrap are not added to `yarn.lock`. If yarn.lock doesn't update automatically after you call `yarn add <packages>`, make sure you run `yarn` again to ensure `yarn.lock` gets updated. Everything else looks good and ready to be merged.

I think you did the right thing. Integrity is to make sure that dependencies are consistent so I guess as long the application can run normally. it is fine

**Comment by MayKikuchi** [comment]
I also think it's fine... as long as it works, as long as we have a copy that works

**Pull request merged**
